name: Borderless Designs
favicon: null
layout_spectrum: 0.49534
typography_spectrum: 0.24043
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#020202'
    - '#4d4d4d'
    - '#cd796e'
    - '#a83730'
  brandStrength: 0.5
  lightness: 0.8370506102219224
  saturation: 0.17512904992327094
  rhythmicContrast: 0.294753095600754
purpose: []
